### ISSUE TITLE
Support Firefox

### ISSUE THREAD

**Issue by SirMishaa** [busybox11/codesearch#3]
Firefox should be supported, package format is different that wy this isn't for the moment. 

See : [https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension](https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension)

**Comment by busybox11** [comment]
The extension was working correctly, a permission was missing - and it is optional on Chrome.
