### ISSUE TITLE
It does not work anymore ?

### ISSUE THREAD

**Issue by clementwzk** [busybox11/codesearch#6]
The extension doesn't seem to work anymore :/

**Comment by busybox11** [comment]
Oh indeed, Google seem to have changed their search page structure.
I'm going to rework it ASAP.
Thanks for the issue!

**Comment by busybox11** [comment]
It seems that it's fixed now. Closing this.

**Comment by clementwzk** [comment]
The extension has not been updated

**Comment by busybox11** [comment]
Oh yeah indeed. I might have forgotten to push. Gotta do it tonight.
